[package]
name = "stew"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.5"
aws-sdk-cloudwatch = "1.44.0"
color-eyre = "0.6.3"
ratatui = "0.28.1"
tokio = { version = "1.39.3", features = ["full"] }
